version: ">= 0.14.0"

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-ca-certificate/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-ca-certificate/actions/workflows/test.yml)

  *This module is no longer maintained as it has been integrated into the [nac-aci](https://github.com/netascode/terraform-aci-nac-aci) module.*

  # Terraform ACI CA Certificate Module

  Manages ACI CA Certificate

  Location in GUI:
  `Admin` » `AAA` » `Security` » `Public Key Management` » `Certificate Authorities`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
